name: Prepare Z3

on:
  # Defining workflow_call means that this workflow can be called from
  # your main workflow job
  workflow_call:

jobs:
  install-z3:
    runs-on: ubuntu-latest
    steps:
      - name: Install Z3
        run: |
          sudo apt update 
          sudo apt install git libz3-dev curl gcc pkg-config libssl-dev clang cmake -y
