name: Prepare Z3

on:
  # Defining workflow_call means that this workflow can be called from
  # your main workflow job
  workflow_call:

jobs:
  greeter:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "Hello!"
          echo "Plan is: ${PLAN}"
          apt update && apt install git libz3-dev curl gcc pkg-config libssl-dev clang cmake -y
